[build]
  # Use a verboser build script to help capture useful diagnostics if the build fails on Netlify
  command = "npm run build:netlify"
  publish = "dist"

[context.production.environment]
  # Lock node version across builds to ensure consistency with local dev
  NODE_VERSION = "18"
